# Generated by Django 5.0.9 on 2026-01-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Project', max_length=255, verbose_name='Page Title')),
                ('description', models.TextField(verbose_name='Main Description')),
                ('mission', models.TextField(blank=True, verbose_name='Our Mission')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='About Image')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us Page',
            },
        ),
    ]
