# Generated by Django 5.0.9 on 2026-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us Page', 'verbose_name_plural': 'About Us Page'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='mission',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_01_text',
            field=models.TextField(blank=True, null=True, verbose_name='Card 01 Content'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_01_title',
            field=models.CharField(default='Why Book Buddy Exists', max_length=255, verbose_name='Card 01 Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_02_list',
            field=models.TextField(blank=True, null=True, verbose_name='Card 02 List Items'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_02_title',
            field=models.CharField(default='Why Families Choose Us', max_length=255, verbose_name='Card 02 Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_03_list',
            field=models.TextField(blank=True, null=True, verbose_name='Card 03 List Items'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_03_title',
            field=models.CharField(default='What Makes Us Different', max_length=255, verbose_name='Card 03 Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_04_text',
            field=models.TextField(blank=True, null=True, verbose_name='Card 04 Content'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='card_04_title',
            field=models.CharField(default='How We Grow Together', max_length=255, verbose_name='Card 04 Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='quote_text',
            field=models.TextField(blank=True, null=True, verbose_name='Philosophy Quote'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='About Us Page', max_length=255, verbose_name='Admin Page Title'),
        ),
    ]
